git:
  depth: 3

language: java
sudo: false
install: true

services:
 - docker

#addons:
#  sonarcloud:
#    organization: "projectname"
#    token:
#      secure: "token"

jdk: oraclejdk8

before_script:
 - cp config-travis.env config.env

script:
 - cd implementation
 - mvn install -Dskip.surefire.tests=false -Dskip.failsafe.tests=true #sonar:sonar
 - cd ..
 - ./docker_compile_images.sh no-maven
 - timeout 3 docker-compose up -d # start docker-compose for 3 seconds to create the network
 - ./docker_start_images.sh
 - cd implementation
 - mvn verify -Dskip.surefire.tests
 - cd ..


after_script:
 - docker-compose stop
 - docker-compose rm -f

cache:
 directories:
  - '$HOME/.m2/repository'
  - '$HOME/.sonar/cache'