version: '2.1'
services:
  etcd:
    build: ./docker_images/etcd
    ports:
      - "2379:2379"
      - "2380:2380"
      - "4001:4001"
    healthcheck:
      test: curl localhost:4001/v2/keys
      interval: 5s
      timeout: 5s
      retries: 300
  architecture-manager:
    build: ./docker_images/architecture_manager
    env_file: config.env
    links:
      - etcd
  game-engine:
    build: ./docker_images/game_engine
    env_file: config.env
    tty: true
    links:
      - etcd

  drone-thales-gun1:
    build: ./docker_images/drone
    env_file: config.env
    ports:
      - "8001:8000"
    environment:
      DRONE_NAME: "drone-thales-gun1"
      DRONE_TEAM: "teamthales"
      DRONE_COMPONENTS: "gps,gun,radio"
      DRONE_TACTIC: "org.inaetics.dronessimulator.drone.tactic.example.utility.TheoreticalTactic"
#  drone-thales-gun2:
#    build: ./docker_images/drone
#    env_file: config.env
#    ports:
#      - "8002:8000"
#    environment:
#      DRONE_NAME: "drone-thales-gun2"
#      DRONE_TEAM: "teamthales"
#      DRONE_COMPONENTS: "gps,radio,gun"
#      DRONE_TACTIC: "org.inaetics.dronessimulator.drone.tactic.example.utility.TheoreticalTactic"
  drone-thales-radar:
    build: ./docker_images/drone
    env_file: config.env
    ports:
      - "8003:8000"
    environment:
      DRONE_NAME: "drone-thales-radar"
      DRONE_TEAM: "teamthales"
      DRONE_COMPONENTS: "gps,radio,radar"
      DRONE_TACTIC: "org.inaetics.dronessimulator.drone.tactic.example.utility.TheoreticalTactic"


  drone-student-gun1:
    build: ./docker_images/drone
    env_file: config.env
    environment:
      DRONENAME: "drone-student-gun1"
      DRONE_TEAM: "teammarty"
      DRONE_COMPONENTS: "gps,gun,radio"
      DRONE_TACTIC: "org.inaetics.dronessimulator.drone.tactic.example.utility.TheoreticalTactic"
#  drone-student-gun2:
#    build: ./docker_images/drone
#    env_file: config.env
#    environment:
#      DRONENAME: "drone-student-gun2"
#      DRONE_TEAM: "teammarty"
#      DRONE_COMPONENTS: "gps,radio,gun"
#      DRONE_TACTIC: "org.inaetics.dronessimulator.drone.tactic.example.utility.TheoreticalTactic"
  drone-student_radar:
    build: ./docker_images/drone
    env_file: config.env
    environment:
      DRONENAME: "drone-student-radar"
      DRONE_TEAM: "teammarty"
      DRONE_COMPONENTS: "gps,radio,radar"
      DRONE_TACTIC: "org.inaetics.dronessimulator.drone.tactic.example.utility.TheoreticalTactic"
