version: '2.1'
services:
  etcd:
    build: ./docker_images/etcd
    ports:
      - "2379:2379"
      - "2380:2380"
      - "4001:4001"
    healthcheck:
      test: curl localhost:4001/v2/keys
  rabbitmq:
    build: ./docker_images/rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    env_file: config.env
    healthcheck:
      test: /opt/healthcheck.sh
  game-engine:
    build: ./docker_images/game_engine
    env_file: config.env
    tty: true
  drone:
    build: ./docker_images/drone
    env_file: config.env
  architecture-manager:
    build: ./docker_images/architecture_manager
    env_file: config.env
