version: '2.1'
services:

  drone-thales_1:
    build: ./docker_images/drone
    env_file: config.env
    environment:
      DRONE_NAME: "drone-thales-1"
      DRONE_TEAM: "teamthales"
      DRONE_COMPONENTS: "gps,gun,radio"
      DRONE_TACTIC: "org.inaetics.dronessimulator.drone.tactic.example.basic.BasicTactic"

  drone-thales_2:
    build: ./docker_images/drone
    env_file: config.env
    environment:
      DRONE_NAME: "drone-thales-2"
      DRONE_TEAM: "teamthales"
      DRONE_COMPONENTS: "gps,radio,radar"
      DRONE_TACTIC: "org.inaetics.dronessimulator.drone.tactic.example.basic.BasicTactic"

  drone-student_1:
    build: ./docker_images/drone
    env_file: config.env
    environment:
      DRONE_NAME: "drone-student-1"
      DRONE_TEAM: "teamstudent"
      DRONE_COMPONENTS: "gps,gun,radio"
      DRONE_TACTIC: "org.inaetics.dronessimulator.drone.tactic.example.basic.BasicTactic"

  drone-student_2:
    build: ./docker_images/drone
    env_file: config.env
    environment:
      DRONE_NAME: "drone-student-2"
      DRONE_TEAM: "teamstudent"
      DRONE_COMPONENTS: "gps,radio,radar"
      DRONE_TACTIC: "org.inaetics.dronessimulator.drone.tactic.example.basic.BasicTactic"