version: '2.1'
services:
  etcd:
    build: ./docker_images/etcd
    ports:
      - "2379:2379"
      - "2380:2380"
      - "4001:4001"
    healthcheck:
      test: curl localhost:4001/v2/keys
  rabbitmq:
    build: ./docker_images/rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    env_file: config.env
    healthcheck:
      test: /opt/healthcheck.sh
    depends_on:
      etcd:
        condition: service_healthy
  architecture-manager:
    build: ./docker_images/architecture_manager
    env_file: config.env
    depends_on:
      rabbitmq:
        condition: service_healthy
  game-engine:
    build: ./docker_images/game_engine
    env_file: config.env
    tty: true
    depends_on:
      rabbitmq:
        condition: service_healthy


  drone-thales_1:
    build: ./docker_images/drone
    env_file: config.env
    depends_on:
      rabbitmq:
        condition: service_healthy
    environment:
      DRONE_TEAM: "teamthales"
      DRONE_COMPONENTS: "gps,radar,radio"
  drone-thales_2:
    build: ./docker_images/drone
    env_file: config.env
    depends_on:
      rabbitmq:
        condition: service_healthy
    environment:
      DRONE_TEAM: "teamthales"
      DRONE_COMPONENTS: "gps,radio,gun"
  drone-thales_3:
      build: ./docker_images/drone
      env_file: config.env
      depends_on:
        rabbitmq:
          condition: service_healthy
      environment:
        DRONE_TEAM: "teamthales"
        DRONE_COMPONENTS: "gps,radio,gun"


  drone-student_1:
    build: ./docker_images/drone
    env_file: config.env
    depends_on:
      rabbitmq:
        condition: service_healthy
    environment:
      DRONE_TEAM: "teamstudent"
      DRONE_COMPONENTS: "gps,radar,radio,gun"
