version: '2.1'
services:
  etcd:
    build: ./docker_images/etcd
    ports:
      - "2379:2379"
      - "2380:2380"
      - "4001:4001"
    healthcheck:
      test: curl localhost:4001/v2/keys
      interval: 5s
      timeout: 5s
      retries: 300
  rabbitmq:
    build: ./docker_images/rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    env_file: config.env
    healthcheck:
      test: /opt/healthcheck.sh
      interval: 5s
      timeout: 5s
      retries: 300
    depends_on:
      etcd:
        condition: service_healthy
  architecture-manager:
    build: ./docker_images/architecture_manager
    env_file: config.env
    depends_on:
      rabbitmq:
        condition: service_healthy
  game-engine:
    build: ./docker_images/game_engine
    env_file: config.env
    tty: true
    depends_on:
      rabbitmq:
        condition: service_healthy


  drone-thales_1:
    build: ./docker_images/drone
    env_file: config.env
    depends_on:
      rabbitmq:
        condition: service_healthy
    ports:
      - "8001:8000"
    environment:
      DRONE_NAME: "drone-thales-1"
      DRONE_TEAM: "teamthales"
      DRONE_COMPONENTS: "gps,gun,radio"
      DRONE_TACTIC: "org.inaetics.dronessimulator.drone.tactic.example.utility.TheoreticalTactic"
  drone-thales_2:
    build: ./docker_images/drone
    env_file: config.env
    depends_on:
      rabbitmq:
        condition: service_healthy
    ports:
      - "8002:8000"
    environment:
      DRONE_NAME: "drone-thales-2"
      DRONE_TEAM: "teamthales"
      DRONE_COMPONENTS: "gps,radio,radar"
      DRONE_TACTIC: "org.inaetics.dronessimulator.drone.tactic.example.utility.TheoreticalTactic"
  drone-thales_3:
    build: ./docker_images/drone
    env_file: config.env
    depends_on:
      rabbitmq:
        condition: service_healthy
    ports:
      - "8003:8000"
    environment:
      DRONE_NAME: "drone-thales-3"
      DRONE_TEAM: "teamthales"
      DRONE_COMPONENTS: "gps,radio,gun"
      DRONE_TACTIC: "org.inaetics.dronessimulator.drone.tactic.example.utility.TheoreticalTactic"


  drone-student_1:
    build: ./docker_images/drone
    env_file: config.env
    depends_on:
      rabbitmq:
        condition: service_healthy
    environment:
      DRONE_TEAM: "teamstudent"
      DRONE_COMPONENTS: "gps,radar,radio,gun"
      DRONE_TACTIC: "org.inaetics.dronessimulator.drone.tactic.example.SimpleTactic"
