version: '2.1'
services:
  etcd:
    build: ./docker_images/etcd
    ports:
      - "2379:2379"
      - "2380:2380"
      - "4001:4001"
    healthcheck:
      test: curl localhost:4001/v2/keys
  rabbitmq:
    build: ./docker_images/rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    env_file: config.env
    healthcheck:
      test: /opt/healthcheck.sh
    depends_on:
      etcd:
        condition: service_healthy
  architecture-manager:
    build: ./docker_images/architecture_manager
    env_file: config.env
    depends_on:
      rabbitmq:
        condition: service_healthy
  game-engine:
    build: ./docker_images/game_engine
    env_file: config.env
    tty: true
    depends_on:
      rabbitmq:
        condition: service_healthy
  drone-team2_1:
    build: ./docker_images/drone
    env_file: config.env
    depends_on:
      rabbitmq:
        condition: service_healthy
    environment:
      DRONE_TEAM: "team2"
      DRONE_COMPONENTS: "gps,gun,radar,radio"
  drone-team1_1:
    build: ./docker_images/drone
    env_file: config.env
    environment:
      DRONE_TEAM: "team1"
      DRONE_COMPONENTS: "gps,radar,gun,radio"
    depends_on:
      rabbitmq:
        condition: service_healthy
  drone-team2_2:
    build: ./docker_images/drone
    env_file: config.env
    environment:
      DRONE_TEAM: "team1"
      DRONE_COMPONENTS: "gps,radar,gun,radio"
    depends_on:
      rabbitmq:
        condition: service_healthy
